export default [{
  label: '快速开始',
  children: [{
    name: "Install",
    label: "安装",
    path: '/doc/install'
  }]
}, {
  label: '基础组件',
  children: [{
    name: 'Icon',
    label: '图标',
    path: '/doc/icon'
  }, {
    name: 'Button',
    label: '按钮',
    path: '/doc/button'
  }, {
    name: 'Input',
    label: '输入框',
    path: '/doc/input'
  }, {
    name: 'Select',
    label: '选项',
    path: '/doc/select'
  }, {
    name: 'Cascader',
    label: '级联选择',
    path: '/doc/cascader'
  }, {
    name: 'Radio',
    label: '单选框',
    path: '/doc/radio'
  }, {
    name: 'Checkbox',
    label: '复选框',
    path: '/doc/checkbox'
  }, {
    name: 'Switch',
    label: '开关',
    path: '/doc/switch'
  }, {
    name: 'TimePicker',
    label: '时间选择器',
    path: '/doc/time-picker'
  }, {
    name: 'DatePicker',
    label: '日期选择器',
    path: '/doc/date-picker'
  },{
    name: 'Table',
    label: '表格',
    path: '/doc/table'
  },{
    name: 'Warning',
    label: '警告框',
    path: '/doc/warning'
  }]
}, {
  label: '弹出层',
  children: [{
    name: 'Dialog',
    label: '对话框',
    path: '/doc/dialog'
  }, {
    name: 'Alert',
    label: '弹窗',
    path: '/doc/alert'
  }, {
    name: 'Message',
    label: '消息',
    path: '/doc/message'
  }, {
    name: 'Notification',
    label: '通知',
    path: '/doc/notification'
  }, {
    name: 'Drawer',
    label: '抽屉',
    path: '/doc/drawer'
  }, {
    name: 'Tooltip',
    label: '文本提示',
    path: '/doc/tooltip'
  }]
}, {
  label: '其他',
  children: [{
    name: 'Divider',
    label: '分割线',
    path: '/doc/divider'
  }, {
    name: 'Step',
    label: '步骤条',
    path: '/doc/step'
  }, {
    name: 'Tabs',
    label: '标签页',
    path: '/doc/tabs'
  }, {
    name: 'Loading',
    label: '加载',
    path: '/doc/loading'
  }, {
    name: 'Empty',
    label: '空状态',
    path: '/doc/empty'
  }, {
    name: 'Tree',
    label: '树形组件',
    path: '/doc/tree'
  }, {
    name: 'Menu',
    label: '侧边栏菜单组件',
    path: '/doc/menu'
  }]
}]